repo:
  - ./*

# Add 'document' to any changes within 'document' folder or any subfolders
document:
  - documents/*
  - documents/**/*

ohp-client:
  - open-hackathon-client/*
  - open-hackathon-client/**/*

ohp-server:
  - open-hackathon-server/*
  - open-hackathon-server/**/*
