apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kaiyuanshe.cn/app: ohp
    haking.kaiyuanshe.cn/service: client
  name: ohp-client
  namespace: ohp
spec:
  replicas: 1
  selector:
    matchLabels:
      haking.kaiyuanshe.cn/service: client
  template:
    metadata:
      labels:
        haking.kaiyuanshe.cn/service: client
    spec:
      containers:
      - image: kaiyuanshe/hackathon-client
        name: ohp-client
        env:
          - name: HACKATHON_SERVER
            value: ohp-server
          - name: HACKATHON_SERVER_PORT
            value: '15000'
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kaiyuanshe.cn/app: ohp
    haking.kaiyuanshe.cn/service: client
  name: ohp-client
  namespace: ohp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    haking.kaiyuanshe.cn/service: client
  type: NodePort
