---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
  - name: default
    data_bag_path: "test/integration/default/data_bags"
    run_list:
      - recipe[databag_item::integration_test]
    attributes:
        from_env_1: "from_env_value_1"
        from_env_2:
          - "from_env_value_2_1"
          - "from_env_value_2_2"
        from_env_3:
          from_env_3_1: "from_env_value_3_1"
        key4:
          from_env_4_1: "from_env_value4_1"
          from_env_4_2:
            - "from_env_value4_2_1"
            - "from_env_value4_2_2"
          from_env_4_3: 
            from_env_4_3_1: "from_env_value4_3_1"
        from_env_5: false
        from_env_6: true
        key7: 
          from_env_7_1: true
          from_env_7_2: false
        key8: "value_from_environment"
        key9:
          key9.2:
            key9.2.1: "value_from_env_9.2.1"
